spring:
  profiles:
    active: dev
  datasource:
    initialization-mode: always
    url: jdbc:mysql://aa1abo1dbh1vckr.cxtvmghsbw6d.ap-northeast-1.rds.amazonaws.com:3306/ebdb
    username: admin
    password: awsawsaws
server: 
  port: 5000
---
spring:
  profiles:
    active: dev
  datasource:
    initialization-mode: always
    url: jdbc:mysql://localhost:3306/mydb?serverTimezone=JST
    username: root
    password: kururu966
server: 
  port: 8080