spring:
  datasource:
   url: jdbc:mysql://localhost:3306/mydb?serverTimezone=JST
   username: root
   password: kururu966
server:
  port: 5000
---
spring:
 config:
  activate:
   on-profile: dev
 datasource:
  initialization-mode: always
  url: jdbc:mysql://aa1kizjk6ybrfz.cxtvmghsbw6d.ap-northeast-1.rds.amazonaws.com:3306/ebdb
  username: root
  password: kururu966