CREATE TABLE IF NOT EXISTS ramen(
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  shop VARCHAR(255) NOT NULL,
  type VARCHAR(255) NOT NULL,
  star VARCHAR(255) NOT NULL,
  day date NOT NULL,
  pic text,
  person VARCHAR(255) NOT NULL
);


CREATE TABLE IF NOT EXISTS user(
  userId BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(64) NOT NULL,
  password VARCHAR(128) NOT NULL,
  role VARCHAR(255) NOT NULL
);

